### ISSUE TITLE
User History Component Display Without Data

### ISSUE THREAD

**Issue by warrenlyr** [warrenlyr/CSS566-Final-Project#111]
Currently, the User History component displays a table header only when there is no data returned from the API:
![image](https://github.com/warrenlyr/CSS566-Final-Project/assets/29391926/44f93bf4-4192-49f8-b94d-776c4d51e6d0)

It's better to have some text to display instead of only showing the table header (Also it's better to not show the header either if there's no data).
For example, the Leaderboard component will display "No scores to show" when there's no data returned from the API:
![image](https://github.com/warrenlyr/CSS566-Final-Project/assets/29391926/7c73982c-58e1-49b0-b979-4595c9d97299)

**Comment by Barack-Liu** [comment]
User History Component Display Without Data #111 fixed
